apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: ams-production
spec:
  selector:
    app: student-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP
