apiVersion: v1
kind: Service
metadata:
  name: org-service
  namespace: ams-production
spec:
  selector:
    app: org-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
