apiVersion: v1
kind: Service
metadata:
  name: campus-service
  namespace: ams-production
spec:
  selector:
    app: campus-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP
