apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: ams-production
spec:
  selector:
    app: result-service
  ports:
    - protocol: TCP
      port: 8007
      targetPort: 8007
  type: ClusterIP
